// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmzpqcr5gDzpK_DTr1OcMQaNHfC0c7GCY',
    appId: '1:428862303673:web:f19b453d360c8cf7b39a68',
    messagingSenderId: '428862303673',
    projectId: 'chatapp-cde34',
    authDomain: 'chatapp-cde34.firebaseapp.com',
    storageBucket: 'chatapp-cde34.appspot.com',
    measurementId: 'G-623KP66P8T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCe5w5xlSpFO8ZBNSugtJ9tt_TBVlTk8xs',
    appId: '1:428862303673:android:e6fb97df47c7f84eb39a68',
    messagingSenderId: '428862303673',
    projectId: 'chatapp-cde34',
    storageBucket: 'chatapp-cde34.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9a5td4zvWBYZdD4jVeWnoZ8xv0N0d4qg',
    appId: '1:428862303673:ios:48ecf94eb0c45a03b39a68',
    messagingSenderId: '428862303673',
    projectId: 'chatapp-cde34',
    storageBucket: 'chatapp-cde34.appspot.com',
    iosBundleId: 'com.example.flutterChatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD9a5td4zvWBYZdD4jVeWnoZ8xv0N0d4qg',
    appId: '1:428862303673:ios:5ef8738084ff136db39a68',
    messagingSenderId: '428862303673',
    projectId: 'chatapp-cde34',
    storageBucket: 'chatapp-cde34.appspot.com',
    iosBundleId: 'com.example.flutterChatApp.RunnerTests',
  );
}
